@startuml
actor "Aluno" as aluno
actor "Professor" as professor
actor "Empresa Parceira" as empresa

aluno --> (Cadastro de Aluno)
aluno --> (Selecionar Instituição)
aluno --> (Consultar Saldo de Moedas)
aluno --> (Consultar Extrato de Transações)
aluno --> (Resgatar Vantagem)

professor --> (Enviar Moedas)
professor --> (Consultar Saldo de Moedas)
professor --> (Consultar Extrato de Transações)

empresa --> (Cadastro de Empresa)
empresa --> (Cadastro de Vantagem)

aluno --> (Login e Autenticação)
professor --> (Login e Autenticação)
empresa --> (Login e Autenticação)
@enduml